cc_library(
    name = 'meta_tree',
    srcs = 'meta_tree.cc',
    deps = [
        '//rsfs/proto:status_code_proto',
        '//rsfs/proto:meta_tree_proto',
        '//rsfs/proto:master_rpc_proto',
        '//toft/system/threading:_sync_object',
        '//thirdparty/leveldb:leveldb'
    ]
)
